### ISSUE TITLE
Boolean circuit with boolify-width 1 is incorrectly rejected for being an arithmetic circuit

### ISSUE THREAD

**Issue by voltrevo** [voltrevo/mpz-ts#1]
reproduce by using this circuit in the manualTest.ts demo:

```ts
  const circuit = summon.compileBoolean('/src/main.ts', 1, {
    '/src/main.ts': `
      export default function main(a: number, b: number) {
        return a + b;
      }
    `,
  });
```

output

```
➜  mpz-ts git:(main) bun run manualTest.ts
402 | 
403 | function __wbg_get_imports() {
404 |     const imports = {};
405 |     imports.wbg = {};
406 |     imports.wbg.__wbindgen_error_new = function(arg0, arg1) {
407 |         const ret = new Error(getStringFromWasm0(arg0, arg1));
                          ^
error: Arithmetic circuit not supported (boolean circuits only)
      at /Users/dev/workspaces/ethf/mpz-ts/srcWasm/mpz_ts_wasm.js:407:21
      at <?>.wasm-function[269]
      at <?>.wasm-function[92]
      at <?>.wasm-function[374]
      at <?>.wasm-function[751]
      at <?>.wasm-function[1416]
      at <?>.wasm-function[1415]
      at __wbg_adapter_54 (/Users/dev/workspaces/ethf/mpz-ts/srcWasm/mpz_ts_wasm.js:231:10)
      at real (/Users/dev/workspaces/ethf/mpz-ts/srcWasm/mpz_ts_wasm.js:216:20)
```

**Comment by voltrevo** [comment]
[fixed](https://github.com/voltrevo/mpz-ts/commit/b779c837f66a856fef3485d45f657533a0008eb9)
